{{ config(materialized="table") }}

SELECT
date,
month_date,
unix_month_date,
site,
site_domain_subfolder site_domain,
hostname,
site_section,
country,
source,
medium,
deviceCategory,
case when keyword_text = 'Not Attributed' then '-' else keyword_top_landing_page end as keyword_top_landing_page,
competitor_site_domain,
competitor_highest_ranking_page,
keyword_text,
keyword_intent,
keyword_category,
keyword_subcategory,
keyword_brand,
page_type,
is_local_result,
is_featured_snippet,
has_site_links,
has_reviews,
has_video,
page_serp_features,
tags,
share_of_voice,
lag(share_of_voice) over(w1) share_of_voice_mom,
rank,
lag(rank) over(w1) rank_mom,
impressions,
lag(impressions) over(w1) impressions_mom,
clicks,
lag(clicks) over(w1) clicks_mom,
avg_position,
lag(avg_position) over(w1) avg_position_mom,
competitor_rank,
lag(competitor_rank) over(w1) competitor_rank_mom,
search_volume,
lag(search_volume) over(w1) search_volume_mom,
avg_cpc,
lag(avg_cpc) over(w1) avg_cpc_mom,
search_volume_competition,
lag(search_volume_competition) over(w1) search_volume_competition_mom,
sessions,
lag(sessions) over(w1) sessions_mom,
pageviews,
lag(pageviews) over(w1) pageviews_mom,
conversions,
lag(conversions) over(w1) conversions_mom
FROM {{ref('agg_accuranker_gsc_ga')}}
WINDOW w1 AS (PARTITION BY site, keyword_text ORDER BY month_date ASC )